const http = require('http');
const routes = require('./routes');
console.log("rebase master");
console.log("useless change1");
console.log("useless change2");
console.log("useless change1");
console.log("useless change2");
console.log("useless change3");
console.log("useless change4");
console.log("useless change5");
const server = http.createServer(routes);
server.listen(3000);